version: "3"

services:
  db:
    image:
      postgres:16.0-alpine3.17
    restart: always
    env_file:
      - backend/.env
    ports:
      - $POSTGRES_PORT:5432
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - backend/.env

volumes:
  db_data:
