  services:
    db:
      image:
        postgres:16.0-alpine3.17
      restart: always
      env_file:
        - backend/.env
      ports:
        - "5432:5432"
      volumes:
        - db_data:/var/lib/postgresql/data
      container_name: postgres-database

    backend:
      build:
        context: ./backend
      volumes:
        - ./backend:/app
      ports:
        - "8000:8000"
      depends_on:
        - db
      env_file:
        - backend/.env
      command: >
        sh -c "python manage.py makemigrations &&
               python manage.py migrate &&
               python manage.py runserver 0.0.0.0:8000"
      container_name: backend

    backend-ws:
      build:
        context: ./backend
      volumes:
        - ./backend:/app
      ports:
        - "8001:8001"
      depends_on:
        - db
        - redis
      env_file:
        - backend/.env
      command: daphne --verbosity 2 -b 0.0.0.0 -p 8001 comments_spa.asgi:application
      container_name: backend-ws

    redis:
      image: redis:alpine
      ports:
        - "6379:6379"
      container_name: redis-database

    redisinsight:
      image: redislabs/redisinsight:latest
      ports:
        - "5540:5540"
      depends_on:
        - redis
      container_name: redisinsight

    celery:
      build:
        context: ./backend
      command:
        celery -A comments_spa worker -l INFO
      container_name: celery-worker

    frontend:
      build:
        context: ./frontend
      volumes:
        - ./frontend:/app
        - /app/node_modules
      depends_on:
        - backend
      ports:
        - "8080:8080"
      environment:
        - CHOKIDAR_USEPOLLING=true
      container_name: frontend
  volumes:
    db_data:
    static_volume:
